---
Name: audiodefinitionconfig
---
SilverStripe\Core\Injector\Injector:
  Psr\SimpleCache\CacheInterface.audioDefinitionCache:
    factory: SilverStripe\Core\Cache\CacheFactory
    constructor:
      namespace: "audioDefinitionCache"

SilverStripe\Forms\HTMLEditor\TinyMCEConfig:
  editor_css:
    - 'dnadesign/silverstripe-audio-definition:client/css/editor.css'
